# Generated by Django 5.1.5 on 2025-11-12 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория сайта',
                'verbose_name_plural': 'Категории сайтов',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50, verbose_name='Тип данных')),
                ('period', models.DateField(verbose_name='Период')),
                ('data', models.JSONField(default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аналитические данные',
                'verbose_name_plural': 'Аналитические данные',
                'unique_together': {('data_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Студенческий билет')),
                ('faculty', models.CharField(blank=True, choices=[('computer_science', 'Компьютерные науки'), ('engineering', 'Инженерия'), ('business', 'Бизнес-администрирование'), ('arts', 'Искусство и гуманитарные науки'), ('science', 'Естественные науки'), ('medicine', 'Медицина')], max_length=50, null=True, verbose_name='Факультет')),
                ('course', models.IntegerField(blank=True, choices=[(1, '1 курс'), (2, '2 курс'), (3, '3 курс'), (4, '4 курс'), (5, '5 курс'), (6, '6 курс')], null=True, verbose_name='Курс')),
                ('group', models.CharField(blank=True, max_length=10, null=True, verbose_name='Группа')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('monitor', 'Староста'), ('curator', 'Куратор'), ('teacher', 'Преподаватель'), ('admin', 'Администратор')], default='student', max_length=10, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('subscriptions', 'Отчет по подпискам'), ('activity', 'Отчет по активности'), ('academic', 'Академический отчет'), ('custom', 'Пользовательский отчет')], max_length=20, verbose_name='Тип отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный отчет')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('target', models.CharField(choices=[('all', 'Все пользователи'), ('students', 'Только студенты'), ('monitors', 'Старосты'), ('curators', 'Кураторы'), ('teachers', 'Преподаватели'), ('group', 'Конкретная группа'), ('course', 'Конкретный курс')], default='all', max_length=10, verbose_name='Целевая аудитория')),
                ('target_group', models.CharField(blank=True, max_length=10, verbose_name='Группа (если выбрана)')),
                ('target_course', models.IntegerField(blank=True, null=True, verbose_name='Курс (если выбран)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('subscription_type', models.CharField(choices=[('auto', 'Автоматическая подписка'), ('manual', 'Требует подтверждения админа')], default='auto', max_length=10, verbose_name='Тип подписки')),
                ('duration_days', models.IntegerField(choices=[(30, '30 дней'), (90, '90 дней'), (180, '180 дней'), (365, '1 год'), (0, 'Бессрочная')], default=30, verbose_name='Длительность подписки (дней)')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Требует подтверждения')),
                ('access_level', models.CharField(choices=[('all', 'Все пользователи'), ('students', 'Только студенты'), ('monitors', 'Старосты и выше'), ('curators', 'Кураторы и выше'), ('teachers', 'Преподаватели и выше')], default='all', max_length=10, verbose_name='Уровень доступа')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.websitecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Веб-сайт',
                'verbose_name_plural': 'Веб-сайты',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('active', 'Активна'), ('expired', 'Истекла'), ('rejected', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Подтверждено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile', verbose_name='Пользователь')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.website', verbose_name='Веб-сайт')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('student', 'website')},
            },
        ),
    ]
