# Generated by Django 5.1.5 on 2025-11-27 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyticsData',
        ),
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студентов'},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
        migrations.RemoveField(
            model_name='website',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='website',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='website',
            name='requires_approval',
        ),
        migrations.RemoveField(
            model_name='website',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='Староста'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.studentprofile', verbose_name='Студент'),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
